//! Repository implementations.

pub mod account_recovery_token_repo;
pub mod api_key_repo;
pub mod audit_event_repo;
pub mod auth_code_repo;
pub mod client_repo;
pub mod device_code_repo;
pub mod email_verification_token_repo;
pub mod federated_identity_repo;
pub mod group_repo;
pub mod group_role_repo;
pub mod identity_provider_repo;
pub mod par_repo;
pub mod password_reset_token_repo;
pub mod realm_repo;
pub mod realm_signing_keys_repo;
pub mod role_repo;
pub mod scope_repo;
pub mod session_repo;
pub mod signing_key_repo;
pub mod social_login_state_repo;
pub mod user_group_repo;
pub mod user_repo;
pub mod user_role_repo;
