import { html } from 'lit-html';
import { BaseComponent } from '../core/component.js';
import { get, post, http } from '../core/http.js';
import { showToast } from '../components/ui/toast.js';
import { handleApiError } from '../utils/error-handler.js';

class SecurityPage extends BaseComponent {
  constructor() { super(); this._state={loading:true,status:null,totpSetup:null,totpCode:'',recoveryCodes:[]}; }
  connectedCallback(){super.connectedCallback();this._load();}
  async _load(){try{this.setState({loading:true});const status=await get('/oidc/account/mfa',this.signal);this.setState({status,loading:false});}catch(e){if(e.name!=='AbortError')handleApiError(e,'Failed to load security settings');this.setState({loading:false});}}
  _b64urlToBytes(v){const p=v.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-v.length%4)%4);return Uint8Array.from(atob(p),c=>c.charCodeAt(0));}
  _bytesToB64url(v){let b='';for(const x of new Uint8Array(v))b+=String.fromCharCode(x);return btoa(b).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  async _startTotp(){try{const setup=await post('/oidc/account/mfa/totp/start',{});this.setState({totpSetup:setup,totpCode:''});}catch(e){handleApiError(e,'Could not start authenticator setup');}}
  async _finishTotp(){try{const out=await post('/oidc/account/mfa/totp/finish',{ceremony_token:this._state.totpSetup.ceremony_token,code:this._state.totpCode,label:'Authenticator app'});this.setState({totpSetup:null,recoveryCodes:out.recovery_codes||[]});showToast('Authenticator app enabled','success');await this._load();}catch(e){handleApiError(e,'The authenticator code was not accepted');}}
  async _addPasskey(){try{const start=await post('/oidc/account/mfa/passkeys/start',{});const options=structuredClone(start.public_key);options.challenge=this._b64urlToBytes(options.challenge);options.user.id=this._b64urlToBytes(options.user.id);options.excludeCredentials=(options.excludeCredentials||[]).map(c=>({...c,id:this._b64urlToBytes(c.id)}));const credential=await navigator.credentials.create({publicKey:options});const transports=credential.response.getTransports?credential.response.getTransports():[];const out=await post('/oidc/account/mfa/passkeys/finish',{ceremony_token:start.ceremony_token,label:'Passkey',response:{id:credential.id,transports,attestationObject:this._bytesToB64url(credential.response.attestationObject),clientDataJSON:this._bytesToB64url(credential.response.clientDataJSON)}});if(out.recovery_codes)this.setState({recoveryCodes:out.recovery_codes});showToast('Passkey added','success');await this._load();}catch(e){if(e.name!=='NotAllowedError')handleApiError(e,'Could not add the passkey');}}
  async _removeTotp(){if(!confirm('Remove this authenticator app?'))return;try{await http('/oidc/account/mfa/totp',{method:'DELETE'});showToast('Authenticator app removed','success');await this._load();}catch(e){handleApiError(e,'Could not remove authenticator');}}
  async _removePasskey(id){if(!confirm('Remove this passkey?'))return;try{await http('/oidc/account/mfa/passkeys',{method:'DELETE',body:JSON.stringify({credential_id:id})});showToast('Passkey removed','success');await this._load();}catch(e){handleApiError(e,'Could not remove passkey');}}
  async _regenerate(){if(!confirm('Replace all existing recovery codes?'))return;try{const out=await post('/oidc/account/mfa/recovery-codes',{});this.setState({recoveryCodes:out.recovery_codes});showToast('New recovery codes created','success');await this._load();}catch(e){handleApiError(e,'Could not create recovery codes');}}
  _downloadCodes(){const blob=new Blob([this._state.recoveryCodes.join('\n')+'\n'],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='oidc-hub-recovery-codes.txt';a.click();URL.revokeObjectURL(a.href);}
  template(){const {loading,status,totpSetup,recoveryCodes}=this._state;return html`<c-page-layout title="Sign-in security">
    ${loading?html`<p>Loading...</p>`:html`
      ${recoveryCodes.length?html`<section class="card" style="border:2px solid var(--color-warning);margin-bottom:1rem"><h2>Save your recovery codes</h2><p>Each code works once. Store them somewhere private. They will not be shown again.</p><pre class="api-key-raw">${recoveryCodes.join('\n')}</pre><c-button @click=${()=>this._downloadCodes()}>Download codes</c-button></section>`:''}
      <section class="card"><h2>Authenticator app</h2>${status?.totp?html`<p><strong>${status.totp.label}</strong> is enabled.</p><c-button variant="danger" @click=${()=>this._removeTotp()}>Remove</c-button>`:html`<p>Use a six-digit code from an authenticator app when you sign in.</p><c-button @click=${()=>this._startTotp()}>Set up authenticator</c-button>`}
      ${totpSetup?html`<div class="section"><p>In your authenticator app, add an account with this setup key:</p><pre class="api-key-raw">${totpSetup.secret}</pre><details><summary>Setup link</summary><p class="api-key-raw">${totpSetup.otpauth_uri}</p></details><div class="field"><label class="field-label">Enter the six-digit code</label><input class="field-input" autocomplete="one-time-code" .value=${this._state.totpCode} @input=${e=>this.setState({totpCode:e.target.value})}></div><c-button @click=${()=>this._finishTotp()}>Verify and enable</c-button></div>`:''}</section>
      <section class="card" style="margin-top:1rem"><h2>Passkeys</h2><p>Use your device screen lock, fingerprint, face, or security key as your second factor.</p><c-button @click=${()=>this._addPasskey()}>Add a passkey</c-button><ul class="item-list" style="margin-top:1rem">${(status?.passkeys||[]).map(p=>html`<li><span><span class="item-name">${p.label}</span><span class="item-desc">Added ${new Date(p.created_at).toLocaleDateString()}</span></span><c-button variant="danger" size="sm" @click=${()=>this._removePasskey(p.id)}>Remove</c-button></li>`)}</ul></section>
      <section class="card" style="margin-top:1rem"><h2>Recovery codes</h2><p>${status?.recovery_codes_remaining||0} unused codes remain.</p><c-button @click=${()=>this._regenerate()} ?disabled=${!status?.totp&&!(status?.passkeys||[]).length}>Generate new codes</c-button></section>
    `}</c-page-layout>`;}
}
customElements.define('security-page',SecurityPage);
