import { html } from 'lit-html';
import { BaseComponent } from '../core/component.js';
import { listAllRealms } from '../services/realm-service.js';
import { listUsers } from '../services/user-service.js';
import { listRoles } from '../services/role-service.js';
import { listGroups } from '../services/group-service.js';
import { listWorkflows,createWorkflow,updateWorkflow,deleteWorkflow,activateWorkflow,listWorkflowExecutions,runDueWorkflows,retryWorkflowExecution,cancelWorkflowExecution } from '../services/workflow-service.js';
import { showToast } from '../components/ui/toast.js';
import { handleApiError } from '../utils/error-handler.js';

const eventSuggestions=['user.created','user.authenticated','user.role_assigned','user.group_assigned','user.account_recovery_completed','user.mfa_reset'];
const conditionLabels={user_enabled:'Account enabled',email_verified:'Email verified',user_attribute_equals:'Attribute equals',inactive_for_days:'Inactive for days',has_role:'Has role',in_group:'In group'};
const actionLabels={disable_user:'Disable user',enable_user:'Enable user',delete_user:'Delete user',add_required_action:'Add required action',remove_required_action:'Remove required action',revoke_sessions:'Sign out user',set_user_attribute:'Set attribute',remove_user_attribute:'Remove attribute',grant_role:'Grant role',revoke_role:'Revoke role',join_group:'Join group',leave_group:'Leave group'};
const requiredActions=[['update_password','Update password'],['verify_email','Verify email'],['update_profile','Update profile'],['configure_mfa','Configure MFA'],['accept_terms','Accept terms']];
const emptyForm=()=>({id:null,name:'',description:'',enabled:true,events:'',scheduled:false,everyHours:24,batchSize:100,conditions:[],steps:[{type:'add_required_action',action:'update_password',afterSeconds:0}]});

class WorkflowsPage extends BaseComponent{
 constructor(){super();this._state={realms:[],realmId:'',workflows:[],executions:[],users:[],roles:[],groups:[],loading:true,saving:false,tab:'workflows',manualUser:'',...emptyForm()}}
 _render(){super._render();queueMicrotask(()=>{this.shadowRoot.querySelectorAll('.builder-row').forEach((row,i)=>{const condition=this._state.conditions[i],selects=row.querySelectorAll('select');if(!condition||!selects[0])return;selects[0].value=condition.type;if(selects[1])selects[1].value=['user_enabled','email_verified'].includes(condition.type)?String(condition.value):condition.refId||''});this.shadowRoot.querySelectorAll('.step').forEach((row,i)=>{const step=this._state.steps[i],selects=row.querySelectorAll('select');if(!step||!selects[0])return;selects[0].value=step.type;if(selects[1])selects[1].value=['add_required_action','remove_required_action'].includes(step.type)?step.action:step.refId||''})})}
 async connectedCallback(){super.connectedCallback();try{const realms=await listAllRealms(this.signal);const realmId=realms[0]?.id||'';this.setState({realms,realmId});if(realmId)await this.load(realmId)}catch(e){handleApiError(e,'Failed to load workflows');this.setState({loading:false})}}
 async load(realmId=this._state.realmId){this.setState({loading:true});try{const [w,x,u,r,g]=await Promise.all([listWorkflows(realmId,this.signal),listWorkflowExecutions(realmId,this.signal),listUsers({realm_id:realmId,limit:500},this.signal),listRoles({realm_id:realmId,limit:500},this.signal),listGroups({realm_id:realmId,limit:500},this.signal)]);this.setState({workflows:w.items||[],executions:x.items||[],users:u.items||[],roles:r.items||[],groups:g.items||[],manualUser:u.items?.[0]?.id||'',loading:false})}catch(e){handleApiError(e,'Failed to load workflow data');this.setState({loading:false})}}
 async realmChanged(e){const realmId=e.target.value;this.setState({realmId,...emptyForm()});await this.load(realmId)}
 parseCondition(c){const out={type:c.type};if(['user_enabled','email_verified'].includes(c.type))out.value=c.value;if(c.type==='user_attribute_equals'){out.name=c.name;out.value=c.textValue}if(c.type==='inactive_for_days')out.days=Number(c.days);if(c.type==='has_role')out.role_id=c.refId;if(c.type==='in_group')out.group_id=c.refId;return out}
 parseStep(s){const action={type:s.type};if(['add_required_action','remove_required_action'].includes(s.type))action.action=s.action;if(['set_user_attribute'].includes(s.type)){action.name=s.name;action.value=s.value}if(s.type==='remove_user_attribute')action.name=s.name;if(['grant_role','revoke_role'].includes(s.type))action.role_id=s.refId;if(['join_group','leave_group'].includes(s.type))action.group_id=s.refId;return{action,after_seconds:Number(s.afterSeconds)||0}}
 body(){const s=this._state;return{name:s.name,description:s.description||null,enabled:s.enabled,trigger_events:s.events.split(',').map(v=>v.trim()).filter(Boolean),conditions:s.conditions.map(c=>this.parseCondition(c)),steps:s.steps.map(x=>this.parseStep(x)),schedule:s.scheduled?{every_seconds:Math.max(60,Math.round(Number(s.everyHours)*3600)),batch_size:Number(s.batchSize)}:null}}
 async save(){this.setState({saving:true});try{const s=this._state;if(s.id)await updateWorkflow(s.realmId,s.id,this.body(),this.signal);else await createWorkflow(s.realmId,this.body(),this.signal);showToast(`Workflow ${s.id?'updated':'created'}`,'success');this.setState({...emptyForm(),saving:false});await this.load()}catch(e){handleApiError(e,'Failed to save workflow');this.setState({saving:false})}}
 edit(w){this.setState({...emptyForm(),id:w.id,name:w.name,description:w.description||'',enabled:w.enabled,events:w.trigger_events.join(', '),scheduled:!!w.schedule,everyHours:w.schedule?w.schedule.every_seconds/3600:24,batchSize:w.schedule?.batch_size||100,conditions:w.conditions.map(c=>({type:c.type,value:c.value,textValue:c.value,name:c.name||'',days:c.days||30,refId:c.role_id||c.group_id||''})),steps:w.steps.map(s=>({type:s.action.type,action:s.action.action||'update_password',name:s.action.name||'',value:s.action.value||'',refId:s.action.role_id||s.action.group_id||'',afterSeconds:s.after_seconds}))});this.shadowRoot.querySelector('.editor')?.scrollIntoView({behavior:'smooth'})}
 async remove(id){if(!confirm('Delete this workflow and cancel its pending executions?'))return;try{await deleteWorkflow(this._state.realmId,id,this.signal);showToast('Workflow deleted','success');await this.load()}catch(e){handleApiError(e,'Failed to delete workflow')}}
 async runDue(){try{const r=await runDueWorkflows(this._state.realmId,this.signal);showToast(`Processed ${r.completed+r.waiting+r.failed} executions`,'success');await this.load()}catch(e){handleApiError(e,'Failed to process due workflows')}}
 async activate(id){if(!this._state.manualUser)return;try{const r=await activateWorkflow(this._state.realmId,id,this._state.manualUser,this.signal);showToast(r.activated?'Workflow activated':r.reason,r.activated?'success':'info');await this.load()}catch(e){handleApiError(e,'Failed to activate workflow')}}
 async executionAction(action,id){try{await(action==='retry'?retryWorkflowExecution:cancelWorkflowExecution)(this._state.realmId,id,this.signal);showToast(action==='retry'?'Execution retried':'Execution cancelled','success');await this.load()}catch(e){handleApiError(e,`Failed to ${action} execution`)}}
 updateCondition(i,patch){const conditions=[...this._state.conditions];conditions[i]={...conditions[i],...patch};this.setState({conditions})}
 addCondition(){this.setState({conditions:[...this._state.conditions,{type:'user_enabled',value:true,textValue:'',name:'',days:30,refId:''}]})}
 removeCondition(i){this.setState({conditions:this._state.conditions.filter((_,n)=>n!==i)})}
 updateStep(i,patch){const steps=[...this._state.steps];steps[i]={...steps[i],...patch};this.setState({steps})}
 addStep(){this.setState({steps:[...this._state.steps,{type:'revoke_sessions',action:'update_password',name:'',value:'',refId:'',afterSeconds:0}]})}
 removeStep(i){if(this._state.steps.length>1)this.setState({steps:this._state.steps.filter((_,n)=>n!==i)})}
 moveStep(i,d){const n=i+d;if(n<0||n>=this._state.steps.length)return;const steps=[...this._state.steps];[steps[i],steps[n]]=[steps[n],steps[i]];this.setState({steps})}
 field(label,key,type='text',hint=''){return html`<div class="field"><label class="field-label">${label}</label><input class="field-input" type=${type} .value=${String(this._state[key])} @input=${e=>this.setState({[key]:e.target.value})}/>${hint?html`<div class="hint">${hint}</div>`:''}</div>`}
 selectOptions(items,selected,label){return items.map(v=>html`<option value=${v.id} ?selected=${v.id===selected}>${label(v)}</option>`)}
 conditionEditor(c,i){const s=this._state;return html`<div class="builder-row"><div class="field"><label class="field-label">Condition</label><select class="field-input" .value=${c.type} @change=${e=>this.updateCondition(i,{type:e.target.value})}>${Object.entries(conditionLabels).map(([v,l])=>html`<option value=${v}>${l}</option>`)}</select></div>${['user_enabled','email_verified'].includes(c.type)?html`<div class="field"><label class="field-label">Must be</label><select class="field-input" .value=${String(c.value)} @change=${e=>this.updateCondition(i,{value:e.target.value==='true'})}><option value="true">Yes</option><option value="false">No</option></select></div>`:''}${c.type==='user_attribute_equals'?html`<div class="field"><label class="field-label">Attribute</label><input class="field-input" .value=${c.name} @input=${e=>this.updateCondition(i,{name:e.target.value})}/></div><div class="field"><label class="field-label">Value</label><input class="field-input" .value=${c.textValue} @input=${e=>this.updateCondition(i,{textValue:e.target.value})}/></div>`:''}${c.type==='inactive_for_days'?html`<div class="field"><label class="field-label">Days</label><input class="field-input" type="number" min="1" .value=${String(c.days)} @input=${e=>this.updateCondition(i,{days:e.target.value})}/></div>`:''}${c.type==='has_role'?html`<div class="field"><label class="field-label">Role</label><select class="field-input" @change=${e=>this.updateCondition(i,{refId:e.target.value})}><option value="">Select a role</option>${this.selectOptions(s.roles,c.refId,v=>v.name)}</select></div>`:''}${c.type==='in_group'?html`<div class="field"><label class="field-label">Group</label><select class="field-input" @change=${e=>this.updateCondition(i,{refId:e.target.value})}><option value="">Select a group</option>${this.selectOptions(s.groups,c.refId,v=>v.name)}</select></div>`:''}<button class="icon-button" title="Remove condition" @click=${()=>this.removeCondition(i)}>×</button></div>`}
 stepEditor(step,i){const s=this._state;return html`<div class="step"><div class="step-number">${i+1}</div><div class="step-fields"><div class="field"><label class="field-label">Action</label><select class="field-input" .value=${step.type} @change=${e=>this.updateStep(i,{type:e.target.value})}>${Object.entries(actionLabels).map(([v,l])=>html`<option value=${v}>${l}</option>`)}</select></div>${['add_required_action','remove_required_action'].includes(step.type)?html`<div class="field"><label class="field-label">Required action</label><select class="field-input" .value=${step.action} @change=${e=>this.updateStep(i,{action:e.target.value})}>${requiredActions.map(([v,l])=>html`<option value=${v}>${l}</option>`)}</select></div>`:''}${['set_user_attribute','remove_user_attribute'].includes(step.type)?html`<div class="field"><label class="field-label">Attribute</label><input class="field-input" .value=${step.name} @input=${e=>this.updateStep(i,{name:e.target.value})}/></div>`:''}${step.type==='set_user_attribute'?html`<div class="field"><label class="field-label">Value</label><input class="field-input" .value=${step.value} @input=${e=>this.updateStep(i,{value:e.target.value})}/></div>`:''}${['grant_role','revoke_role'].includes(step.type)?html`<div class="field"><label class="field-label">Role</label><select class="field-input" @change=${e=>this.updateStep(i,{refId:e.target.value})}><option value="">Select a role</option>${this.selectOptions(s.roles,step.refId,v=>v.name)}</select></div>`:''}${['join_group','leave_group'].includes(step.type)?html`<div class="field"><label class="field-label">Group</label><select class="field-input" @change=${e=>this.updateStep(i,{refId:e.target.value})}><option value="">Select a group</option>${this.selectOptions(s.groups,step.refId,v=>v.name)}</select></div>`:''}<div class="field small"><label class="field-label">Wait before action</label><input class="field-input" type="number" min="0" .value=${String(step.afterSeconds)} @input=${e=>this.updateStep(i,{afterSeconds:e.target.value})}/><div class="hint">seconds</div></div></div><div class="step-buttons"><button class="icon-button" title="Move up" @click=${()=>this.moveStep(i,-1)}>↑</button><button class="icon-button" title="Move down" @click=${()=>this.moveStep(i,1)}>↓</button><button class="icon-button" title="Remove step" @click=${()=>this.removeStep(i)}>×</button></div></div>`}
 template(){const s=this._state;return html`<c-page-layout title="Workflows"><style>.toolbar,.tabs,.actions,.manual{display:flex;gap:.75rem;align-items:center;flex-wrap:wrap}.toolbar{justify-content:space-between;margin-bottom:1rem}.tabs{border-bottom:1px solid var(--color-border);margin-bottom:1rem}.tabs button{padding:.7rem 1rem;border:0;background:none}.tabs .active{border-bottom:2px solid var(--color-primary);font-weight:600}.editor{margin-bottom:1.25rem}.section-title{margin:1.25rem 0 .6rem;font-weight:600}.builder-row,.step{display:flex;gap:.75rem;align-items:flex-start;border:1px solid var(--color-border);border-radius:8px;padding:.75rem;margin:.6rem 0}.builder-row .field,.step-fields .field{margin:0;min-width:150px}.step{background:var(--color-surface-subtle,#f8fafc)}.step-number{border-radius:50%;background:var(--color-primary);color:white;width:28px;height:28px;display:grid;place-items:center;flex:none}.step-fields{display:flex;gap:.75rem;flex-wrap:wrap;flex:1}.step-buttons{display:flex;gap:.2rem}.icon-button{border:1px solid var(--color-border);background:var(--color-surface);border-radius:5px;min-width:32px;height:32px;cursor:pointer}.small{max-width:150px}.status{display:inline-block;padding:.2rem .55rem;border-radius:999px;background:#e2e8f0;font-size:.78rem;text-transform:capitalize}.status.completed{background:#dcfce7;color:#166534}.status.failed{background:#fee2e2;color:#991b1b}.status.waiting,.status.queued{background:#fef3c7;color:#92400e}.workflow-card{display:flex;justify-content:space-between;gap:1rem}.workflow-meta{color:var(--color-text-muted);font-size:.88rem;margin-top:.4rem}.history{width:100%;border-collapse:collapse}.history th,.history td{text-align:left;padding:.7rem;border-bottom:1px solid var(--color-border)}@media(max-width:850px){.builder-row,.step-fields{flex-direction:column}.workflow-card{flex-direction:column}}</style><div class="toolbar"><label>Realm: <select class="field-input" .value=${s.realmId} @change=${e=>this.realmChanged(e)}>${s.realms.map(r=>html`<option value=${r.id}>${r.display_name||r.name}</option>`)}</select></label><c-button @click=${()=>this.runDue()}>Process due actions</c-button></div><div class="tabs"><button class=${s.tab==='workflows'?'active':''} @click=${()=>this.setState({tab:'workflows'})}>Workflows</button><button class=${s.tab==='history'?'active':''} @click=${()=>this.setState({tab:'history'})}>Execution history</button></div>${s.loading?html`<p>Loading...</p>`:s.tab==='history'?this.historyView():this.workflowView()}</c-page-layout>`}
 workflowView(){const s=this._state;return html`<section class="card editor"><h2>${s.id?'Edit workflow':'Create workflow'}</h2><div class="grid-2">${this.field('Name','name')}${this.field('Description','description')}</div><label class="field-checkbox"><input type="checkbox" ?checked=${s.enabled} @change=${e=>this.setState({enabled:e.target.checked})}/> Enabled</label><div class="section-title">Triggers</div>${this.field('Events','events','text','Comma-separated event names. Use user.* to match all user events. Leave empty for manual or scheduled use.')}<datalist id="workflow-events">${eventSuggestions.map(v=>html`<option value=${v}></option>`)}</datalist><label class="field-checkbox"><input type="checkbox" ?checked=${s.scheduled} @change=${e=>this.setState({scheduled:e.target.checked})}/> Run on a schedule</label>${s.scheduled?html`<div class="grid-2">${this.field('Repeat every (hours)','everyHours','number')}${this.field('Users per run','batchSize','number')}</div>`:''}<div class="section-title">Conditions <span class="hint">All conditions must match.</span></div>${s.conditions.map((c,i)=>this.conditionEditor(c,i))}<c-button @click=${()=>this.addCondition()}>Add condition</c-button><div class="section-title">Actions</div>${s.steps.map((step,i)=>this.stepEditor(step,i))}<c-button @click=${()=>this.addStep()}>Add action</c-button><div class="actions" style="margin-top:1rem"><c-button variant="primary" ?disabled=${s.saving||!s.name.trim()||!s.steps.length} @click=${()=>this.save()}>${s.id?'Update':'Create'} workflow</c-button>${s.id?html`<c-button @click=${()=>this.setState(emptyForm())}>Cancel</c-button>`:''}</div></section><section><h2>Configured workflows</h2>${s.workflows.length?s.workflows.map(w=>html`<div class="card workflow-card"><div><strong>${w.name}</strong> <span class="status">${w.enabled?'enabled':'disabled'}</span><div class="workflow-meta">${w.trigger_events.length?w.trigger_events.join(', '):'Manual'}${w.schedule?' · Scheduled':''} · ${w.conditions.length} condition(s) · ${w.steps.length} action(s)</div><p>${w.description||''}</p></div><div class="actions"><c-button @click=${()=>this.edit(w)}>Edit</c-button><c-button variant="danger" @click=${()=>this.remove(w.id)}>Delete</c-button></div></div>`):html`<div class="empty-state">Create a workflow to automate user lifecycle tasks.</div>`}<div class="card"><h3>Run for one user</h3><div class="manual"><select class="field-input" .value=${s.manualUser} @change=${e=>this.setState({manualUser:e.target.value})}>${s.users.map(u=>html`<option value=${u.id}>${u.email}</option>`)}</select><select id="manual-workflow" class="field-input">${s.workflows.filter(w=>w.enabled).map(w=>html`<option value=${w.id}>${w.name}</option>`)}</select><c-button @click=${()=>this.activate(this.shadowRoot.querySelector('#manual-workflow')?.value)}>Run now</c-button></div></div></section>`}
 historyView(){const s=this._state,names=new Map(s.workflows.map(w=>[w.id,w.name]));return s.executions.length?html`<div class="card"><table class="history"><thead><tr><th>Workflow</th><th>User</th><th>Trigger</th><th>Status</th><th>Progress</th><th>Started</th><th>Actions</th></tr></thead><tbody>${s.executions.map(e=>html`<tr><td>${names.get(e.workflow_id)||'Deleted workflow'}</td><td>${s.users.find(u=>u.id===e.user_id)?.email||e.user_id}</td><td>${e.trigger_event}</td><td><span class="status ${e.status}">${e.status}</span>${e.last_error?html`<div class="hint">${e.last_error}</div>`:''}</td><td>Step ${e.current_step}</td><td>${new Date(e.created_at).toLocaleString()}</td><td>${e.status==='failed'?html`<c-button @click=${()=>this.executionAction('retry',e.id)}>Retry</c-button>`:''}${['queued','waiting','failed'].includes(e.status)?html` <c-button @click=${()=>this.executionAction('cancel',e.id)}>Cancel</c-button>`:''}</td></tr>`)}</tbody></table></div>`:html`<div class="empty-state">Workflow executions will appear here.</div>`}
}
customElements.define('workflows-page',WorkflowsPage);
